import React, { useEffect, useState } from 'react';
import { apiRequest } from '../api';

function AdminDashboard() {
  const [data, setData] = useState({ managers: [], hotels: [], orders: [] }); const [report, setReport] = useState([]); const [error, setError] = useState('');
  const [showNotifications, setShowNotifications] = useState(false);
  const load = () => Promise.all([apiRequest('/admin/pending-managers'), apiRequest('/admin/hotels'), apiRequest('/admin/orders'), apiRequest('/admin/commission-report')]).then(([managers, hotels, orders, commission]) => { setData({ managers, hotels, orders }); setReport(commission); }).catch((err) => setError(err.message));
  useEffect(() => { load(); }, []);
  const approve = async (id) => { try { await apiRequest(`/admin/approve-manager/${id}`, { method: 'PUT' }); load(); } catch (err) { setError(err.message); } };
  return <main className="page"><div className="section-heading"><div><p className="eyebrow">Control room</p><h1>Admin dashboard.</h1></div><div className="admin-heading-actions"><div className="notification-wrap"><button className="notification-button" type="button" aria-label={`${data.managers.length} pending approvals`} title="Pending approvals" onClick={() => setShowNotifications(!showNotifications)}><span aria-hidden="true">🔔</span>{data.managers.length > 0 && <strong className="notification-count">{data.managers.length}</strong>}</button>{showNotifications && <div className="notification-panel"><p className="eyebrow">Admin alerts</p><h2>Pending approvals</h2>{data.managers.length ? data.managers.map((manager) => <div className="notification-item" key={manager.id}><div><strong>{manager.name}</strong><small>{manager.email}</small></div><button className="button secondary" onClick={() => approve(manager.id)}>Approve</button></div>) : <p className="muted">You are all caught up.</p>}</div>}</div><p className="muted heading-note">Keep the marketplace moving.</p></div></div>{error && <p className="error">{error}</p>}<div className="metric-grid"><article><span>Pending managers</span><strong>{data.managers.length}</strong></article><article><span>Active hotels</span><strong>{data.hotels.length}</strong></article><article><span>Total orders</span><strong>{data.orders.length}</strong></article></div><section className="dashboard-section"><h2>Manager approvals</h2>{data.managers.length ? data.managers.map((manager) => <article className="data-card" key={manager.id}><div><h3>{manager.name}</h3><p className="muted">{manager.email}</p></div><button className="button secondary" onClick={() => approve(manager.id)}>Approve</button></article>) : <p className="empty">No approvals waiting.</p>}</section><section className="dashboard-section"><h2>Commission report</h2>{report.map((row) => <article className="data-card compact" key={row.hotel_name}><span>{row.hotel_name}</span><strong>${Number(row.total_commission || 0).toFixed(2)}</strong></article>)}</section></main>;
}
export default AdminDashboard;
