import React, { useEffect, useState } from 'react';
import { apiRequest } from '../api';

function ManagerDashboard() {
  const [hotel, setHotel] = useState(null); const [menu, setMenu] = useState([]); const [orders, setOrders] = useState([]); const [earnings, setEarnings] = useState({}); const [form, setForm] = useState({ name: '', description: '', price: '', category: '' }); const [error, setError] = useState('');
  const load = () => Promise.all([apiRequest('/manager/hotel'), apiRequest('/manager/menu'), apiRequest('/manager/orders'), apiRequest('/manager/earnings')]).then(([nextHotel, nextMenu, nextOrders, nextEarnings]) => { setHotel(nextHotel); setMenu(nextMenu); setOrders(nextOrders); setEarnings(nextEarnings); }).catch((err) => setError(err.message));
  useEffect(() => { load(); }, []);
  const addItem = async (event) => { event.preventDefault(); try { await apiRequest('/manager/menu', { method: 'POST', body: JSON.stringify(form) }); setForm({ name: '', description: '', price: '', category: '' }); load(); } catch (err) { setError(err.message); } };
  const status = async (id, nextStatus) => { try { await apiRequest(`/manager/orders/${id}/status`, { method: 'PUT', body: JSON.stringify({ status: nextStatus }) }); load(); } catch (err) { setError(err.message); } };
  return <main className="page"><div className="section-heading"><div><p className="eyebrow">Your kitchen</p><h1>{hotel?.name || 'Manager dashboard.'}</h1></div><p className="muted heading-note">A clear view of today’s service.</p></div>{error && <p className="error">{error}</p>}<div className="metric-grid"><article><span>Completed orders</span><strong>{earnings.total_orders || 0}</strong></article><article><span>Total earnings</span><strong>${Number(earnings.total_earnings || 0).toFixed(2)}</strong></article><article><span>Menu items</span><strong>{menu.length}</strong></article></div><section className="dashboard-section"><h2>Add a menu item</h2><form className="inline-form" onSubmit={addItem}><input required placeholder="Name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input placeholder="Category" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /><input required type="number" min="0" step="0.01" placeholder="Price" value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} /><button className="button primary">Add item</button></form></section><section className="dashboard-section"><h2>Recent orders</h2>{orders.map((order) => <article className="data-card" key={order.id}><div><h3>Order #{order.id}</h3><p className="muted">{order.user_name} · ${Number(order.total_amount).toFixed(2)}</p></div><select value={order.status} onChange={(e) => status(order.id, e.target.value)}><option>pending</option><option>confirmed</option><option>preparing</option><option>ready</option><option>delivered</option><option>completed</option><option>cancelled</option></select></article>)}{!orders.length && <p className="empty">No orders yet.</p>}</section></main>;
}
export default ManagerDashboard;
